---
title: "esm_206_lab_10"
author: "Lauren Harris"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(usethis)
library(janitor)
# new packages
library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
```

## beepr beeps

Use the function `beep()` in the beepr package to make an audio alert when your code is done running

```{r, eval = FALSE}
for (i in rev(seq(1:99))){
  print(paste(i, "bottles of beer on the wall"))
}

# beep(4)
```

##  praise and cowsay

Packages built with a single purpose: to be kind and fun

Will maintain the capitalization from the input

```{r}
praise("${Exclamation}, ${EXCLAMATION}...${exclamation}!!!")

praise("Holy ${creating}, Batman - this code is ${ADJECTIVE}!")
```

Use cowsay::say() to make a character say something to you

## Use paletteer to access thousands of color palettes

```{r}
storms %>% 
  group_by(name) %>% 
  summarize(min_pressure = min(pressure, na.rm = TRUE)) %>% 
  slice_min(n = 10, min_pressure) %>% 
  ggplot(aes(x = min_pressure, y = name)) + 
  geom_col(aes(fill = name)) +
  scale_fill_paletteer_d("khroma::land")
```

## One spatial data example

```{r}
vegetation <- read_sf("doc.kml") %>% 
  clean_names() %>% 
  select(name)

ggplot(data = vegetation) +
  geom_sf(aes(fill = name), color = NA) + 
  theme_minimal() +
  scale_fill_paletteer_d("ggthemes::manyeys") +
  labs(title = "Jornada Basin LTERVegetation", 
       caption = "Source: Jornada LTER")
  
```

```{r}
ggsave(filename = "my_awesome_map.jpg", width = 8, height = 5)
```

